version: '3.7'

networks:
  brokers:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - brokers
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - brokers
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./data/rabbitmq/etc/:/etc/rabbitmq/
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_VHOST=plurall
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - brokers
  sqs:
    image: softwaremill/elasticmq
    ports:
      - '9324:9324'
      - '9325:9325'
    volumes:
      - ./dev/elasticmq.conf:/opt/elasticmq.conf
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - '8161:8161'
      - '61613:61613'
